### ISSUE TITLE
Saving option conflict with jshint

### ISSUE THREAD

**Issue by gubi** [wylst/atom-minifier#9]
Every times that I save the file, the minifier starts before jshint check and so generate this error:

**Atom Version**: 0.187.0
**System**: linux 3.13.0-46-generic
**Thrown From**: [minifier](https://github.com/wylst/atom-minifier) package, v0.2.0

### Stack Trace

Uncaught Unexpected token punc «}», expected punc «,» (line: 2712, col: 3, pos: 95500)

Error
    at new JS_Parse_Error (/home/alessandro/.atom/packages/minifier/node_modules/uglify-js/lib/parse.js:189:18)
    at js_error (/home/alessandro/.atom/packages/minifier/node_modules/uglify-js/lib/parse.js:197:11)
    at croak (/home/alessandro/.atom/packages/minifier/node_modules/uglify-js/lib/parse.js:660:41)
    at token_error (/home/alessandro/.atom/packages/minifier/node_modules/uglify-js/lib/parse.js:664:9)
    at expect_token (/home/alessandro/.atom/packages/minifier/node_modules/uglify-js/lib/parse.js:677:9)
    at expect (/home/alessandro/.atom/packages/minifier/node_modules/uglify-js/lib/parse.js:680:36)
    at expr_list (/home/alessandro/.atom/packages/minifier/node_modules/uglify-js/lib/parse.js:1172:44)
    at subscripts (/home/alessandro/.atom/packages/minifier/node_modules/uglify-js/lib/parse.js:1310:30)
    at subscripts (/home/alessandro/.atom/packages/minifier/node_modules/uglify-js/lib/parse.js:1287:20)
    at subscripts (/home/alessandro/.atom/packages/minifier/node_modules/uglify-js/lib/parse.js:1307:20)

```
At /home/alessandro/.atom/packages/minifier/node_modules/uglify-js/lib/parse.js:197

Error
    at new JS_Parse_Error (/home/alessandro/.atom/packages/minifier/node_modules/uglify-js/lib/parse.js:189:18)
    at js_error (/home/alessandro/.atom/packages/minifier/node_modules/uglify-js/lib/parse.js:197:11)
    at croak (/home/alessandro/.atom/packages/minifier/node_modules/uglify-js/lib/parse.js:660:41)
    at token_error (/home/alessandro/.atom/packages/minifier/node_modules/uglify-js/lib/parse.js:664:9)
    at expect_token (/home/alessandro/.atom/packages/minifier/node_modules/uglify-js/lib/parse.js:677:9)
    at expect (/home/alessandro/.atom/packages/minifier/node_modules/uglify-js/lib/parse.js:680:36)
    at expr_list (/home/alessandro/.atom/packages/minifier/node_modules/uglify-js/lib/parse.js:1172:44)
    at subscripts (/home/alessandro/.atom/packages/minifier/node_modules/uglify-js/lib/parse.js:1310:30)
    at subscripts (/home/alessandro/.atom/packages/minifier/node_modules/uglify-js/lib/parse.js:1287:20)
    at subscripts (/home/alessandro/.atom/packages/minifier/node_modules/uglify-js/lib/parse.js:1307:20)
```

### Commands

```
     -1:16.0 core:copy (atom-text-editor.editor)
     -1:13.1 core:paste (atom-text-editor.editor)
     -1:10.8 snippets:previous-tab-stop (atom-text-editor.editor)
     -1:10.8 editor:outdent-selected-rows (atom-text-editor.editor)
     -1:05.0 editor:toggle-line-comments (atom-text-editor.editor)
     -0:58.5 core:save (atom-text-editor.editor)
     -0:21.4 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:21.4 editor:newline (atom-text-editor.editor.is-focused)
     -0:12.7 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:12.7 editor:newline (atom-text-editor.editor.is-focused)
     -0:07.9 core:move-down (atom-text-editor.editor.is-focused)
     -0:06.7 editor:delete-line (atom-text-editor.editor.is-focused)
     -0:06.2 core:save (atom-text-editor.editor.is-focused)
     -0:04.7 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:04.7 core:cancel (atom-text-editor.editor.is-focused)
     -0:00.7 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-csslint"
    ],
    "projectHome": "/var/www/pgrdg"
  },
  "minifier": {
    "minifyOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.4
docblockr, v0.6.3
linter, v0.12.0
linter-jshint, v0.1.0
linter-php, v0.0.11
markdown-format, v2.5.0
minifier, v0.2.0
pdf-view, v0.17.0
php-getters-setters, v0.3.0
pretty-json, v0.3.2
text-manipulation, v0.4.0

# Dev
No dev packages
```

**Comment by gubi** [comment]
Correcting code produces no changes: I cannot save the file.

**Comment by alfredxing** [comment]
Interesting... I'll try to look into this when I can, but this project isn't under heavy/active development anymore.

Do you know which file is causing the `Uncaught Unexpected token punc «}», expected punc «,» (line: 2712, col: 3, pos: 95500)` error?
